# Generated by Django 3.1.14 on 2022-07-09 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profileapp', '0003_auto_20220423_1322'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
